# Task 2: Array Creation

In [13]:
import numpy as np

# 1. Create 1D array
arr1 = np.array([1, 2, 3, 4])

# 2. Create 2D array
arr2 = np.array([[1, 2], [3, 4]])

# 3. Create 3D array
arr3 = np.array([[[1, 2], [3, 4]]])

# 4. Print all
print("1D Array:")
print(arr1)

print("2D Array:")
print(arr2)

print("3D Array:")
print(arr3)

1D Array:
[1 2 3 4]
2D Array:
[[1 2]
 [3 4]]
3D Array:
[[[1 2]
  [3 4]]]


# Task 3: Properties

In [14]:
import numpy as np

# Create array
arr = np.array([[1, 2], [3, 4]])

# Task 3: Properties

# 1. Print shape
print("Shape:", arr.shape)

# 2. Print dimensions
print("Dimensions:", arr.ndim)

# 3. Print data type
print("Data Type:", arr.dtype)

Shape: (2, 2)
Dimensions: 2
Data Type: int64


# Task 4: Special Arrays


In [15]:
import numpy as np

# 1. Zero matrix
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:\n", zero_matrix)

# 2. Ones matrix
ones_matrix = np.ones((3, 3))
print("Ones Matrix:\n", ones_matrix)

# 3. Identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

# 4. Range array
range_array = np.arange(1, 11)
print("Range Array:\n", range_array)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Range Array:
 [ 1  2  3  4  5  6  7  8  9 10]


# Task 5: Indexing

In [16]:
import numpy as np

# Create arrays
arr_1d = np.array([10, 20, 30, 40, 50])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 1. Access first element
first_element = arr_1d[0]
print("First Element:", first_element)

# 2. Slice array
slice_array = arr_1d[1:4]
print("Sliced Array:", slice_array)

# 3. Access element in 2D
element_2d = arr_2d[1][2]   # row 1, column 2
print("Element from 2D Array:", element_2d)

First Element: 10
Sliced Array: [20 30 40]
Element from 2D Array: 6


# Task 6: Reshaping

In [17]:
import numpy as np

# Create 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# 1. Convert 1D → 2D
arr_2d = arr_1d.reshape(2, 3)
print("1D to 2D:\n", arr_2d)

# 2. Convert 2D → 1D
back_to_1d = arr_2d.reshape(-1)
print("2D to 1D:\n", back_to_1d)

1D to 2D:
 [[1 2 3]
 [4 5 6]]
2D to 1D:
 [1 2 3 4 5 6]
