# Task 2: 1D Practice

In [10]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# 1. Access first element
print(arr[0])

# 2. Access last element
print(arr[-1])

# 3. Slice array
print(arr[1:4])

10
50
[20 30 40]


# Task 3: 2D Practice

In [11]:
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

# 1. Access element
print(arr2[1,2])     # row 2 col 3

# 2. Print row
print(arr2[1])

# 3. Print column
print(arr2[:,1])

6
[4 5 6]
[2 5 8]


# Task 4: 3D Practice

In [12]:
arr3 = np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])

# Access element
print(arr3[0,1,1])

# Print first block
print(arr3[0])

# Print second layer first row
print(arr3[1,0])

4
[[1 2]
 [3 4]]
[5 6]


# Task 5: Slicing

In [13]:
arr = np.array([10,20,30,40,50,60])

# 1. Extract sub-array
print(arr[1:4])

# 2. Use step slicing
print(arr[::2])

# 3. Slice rows and columns
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(arr2[0:2,1:3])

[20 30 40]
[10 30 50]
[[2 3]
 [5 6]]


# Task 6: Boolean Indexing

In [14]:
arr = np.array([10,20,30,40,50])

# 1. Filter values > 25
print(arr[arr > 25])

# 2. Filter values between range
print(arr[(arr >= 20) & (arr <= 40)])

# 3. Replace values conditionally
arr[arr > 30] = 99
print(arr)

[30 40 50]
[20 30 40]
[10 20 30 99 99]
